version: '3.3'
services:
   web:
     build: .
     volumes:
       - ./src/:/var/www/html/
     ports: 
       - 8099:80
   db:
     image: mysql:5.7
     volumes:
       - ./data:/var/lib/mysql       
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: qloapp
       MYSQL_DATABASE: qloapp
       MYSQL_USER: qloapp
       MYSQL_PASSWORD: qloapp        